Chore: CI build rpm

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -51,6 +51,58 @@ jobs:
           *.zip
         if-no-files-found: error
 
+  fedora_build:
+    runs-on: ubuntu-latest
+    container:
+      image: fedora:43
+      volumes:
+        - /usr:/usr-host
+        - /opt:/opt-host
+      options: --privileged
+    steps:
+    - name: Maximize build space
+      run: |
+        df -h
+        rm -rf /usr-host/share/dotnet || true
+        rm -rf /usr-host/share/swift || true
+        rm -rf /usr-host/share/java || true
+        rm -rf /usr-host/local/lib/android || true
+        rm -rf /opt-host/ghc || true
+        rm -rf /opt-host/hostedtoolcache || true
+        rm -rf /opt-host/az || true
+        df -h
+    - uses: actions/checkout@v4
+    - name: Update system
+      run: |
+        dnf -y update || true
+    - name: Install Basic Software
+      run: dnf install -y sudo curl
+    - name: Install Build Dependencies
+      run: dnf install -y rpm-build redhat-rpm-config make gcc clang pkgconfig
+    - name: Install Rust toolchain
+      run:  dnf install -y cargo rust
+    - name: Prepare rpmbuild and build RPM
+      run: |
+        mkdir -p rpmbuild/{SOURCES,SPECS,BUILD,RPMS,SRPMS}
+        cp rpm/atomrootfsinit.spec rpmbuild/SPECS/
+        if [ -f "$PWD/Cargo.lock" ]; then
+          echo "Fedora is a whiny baby and refuses to use dependencies that are told to be used."
+          rm -f $PWD/Cargo.lock
+        else
+          echo "Cargo.lock not found, skipping removal"
+        fi
+        rpmbuild --define "_topdir $PWD/rpmbuild" --define "_sourcedir $PWD" --define "version ${GITHUB_REF#refs/*/}" -ba rpmbuild/SPECS/atomrootfsinit.spec
+    - name: Move rpms
+      run: |
+        mv rpmbuild/RPMS/*/*.rpm . || true
+    - name: Upload package artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: fedora-package
+        path: |
+          *.rpm
+        if-no-files-found: error
+
   bookworm_build:
     runs-on: ubuntu-latest
     container: 
@@ -157,7 +209,7 @@ jobs:
 
   make-release:
     runs-on: ubuntu-latest
-    needs: [prepare, static_build, bookworm_build, trixie_build]
+    needs: [prepare, static_build, bookworm_build, trixie_build, fedora_build]
     steps:
       - name: Download static artifacts
         uses: actions/download-artifact@v4
@@ -186,4 +238,5 @@ jobs:
           fail_on_unmatched_files: true
           files: |
             *.zip
+            *.rpm
             *.deb
